### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by TheHorseFly** [lightning2401/northstar#7]
When I try to start the mod on a server, it gives this error:

[00:13:56] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class com/lightning/northstar/mixin/dimensionstuff/FogRendererMixin for invalid dist DEDICATED_SERVER
[00:13:56] [main/FATAL] [mixin/]: Mixin prepare failed preparing dimensionstuff.FogRendererMixin in northstar.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Attempted to load class com/lightning/northstar/mixin/dimensionstuff/FogRendererMixin for invalid dist DEDICATED_SERVER

it then crashes, spewing a bunch of log stuff (can put in pastebin if needed)

**Comment by BraveJamstar** [comment]
I have the same error. The error seems to be caused by the mixins for the mod. These mixins weren't made to run on the server version of forge so that's why it was crashing as said with "invalid dist DEDICATED_SERVER." I was able to get northstar to run by removing these mixins but the game was extremely broken and nothing from it worked. I did this by removing the mixins but also adding icu to src/main/java/com. The game would flip out with liquids and blocks. For example if a placed a door. It would turn into water. If I placed a gear it would turn into water as well. 

ICU: https://gitlab.com/gitlab-org/build/omnibus-mirror/libicu/-/tree/93fde1c459ec73272361b311ee0258ecd57224cb/icu4j/main/classes/core/src/com

Full Error before my fixes: 
```
[15:14:43] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class com/lightning/northstar/mixin/dimensionstuff/FogRendererMixin for invalid dist DEDICATED_SERVER
[15:14:43] [main/FATAL] [mixin/]: Mixin prepare failed preparing dimensionstuff.FogRendererMixin in northstar.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Attempted to load class com/lightning/northstar/mixin/dimensionstuff/FogRendererMixin for invalid dist DEDICATED_SERVER
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Attempted to load class com/lightning/northstar/mixin/dimensionstuff/FogRendererMixin for invalid dist DEDICATED_SERVER
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:864) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:850) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:775) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar%2354!/:10.0.8+10.0.8+main.0ef7e830] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:632) ~[?:?] {}
        at java.lang.Class.forName(Class.java:545) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.4.2.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.RuntimeException: Attempted to load class com/lightning/northstar/mixin/dimensionstuff/FogRendererMixin for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.4.2.jar%2367!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.getMaybeTransformedClassBytes(ModuleClassLoader.java:250) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:58) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$10(LaunchPluginHandler.java:100) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:222) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1311) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        ... 28 more
Exception in thread "main" java.lang.RuntimeException: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [northstar.mixins.json:dimensionstuff.FogRendererMixin] from phase [DEFAULT] in config [northstar.mixins.json] FAILED during PREPARE
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [northstar.mixins.json:dimensionstuff.FogRendererMixin] from phase [DEFAULT] in config [northstar.mixins.json] FAILED during PREPARE
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:584)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:632)
        at java.base/java.lang.Class.forName(Class.java:545)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.4.2/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Attempted to load class com/lightning/northstar/mixin/dimensionstuff/FogRendererMixin for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:864)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:850)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:775)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539)
        ... 25 more
Caused by: java.lang.RuntimeException: Attempted to load class com/lightning/northstar/mixin/dimensionstuff/FogRendererMixin for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.4.2/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.getMaybeTransformedClassBytes(ModuleClassLoader.java:250)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:58)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$10(LaunchPluginHandler.java:100)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:222)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1311)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857)
```










OS: Ubuntu 22.04
Forge version: 1.19.2 - 43.4.2
Northstar version: 0.1a
Minecraft version: 1.19.2

**Comment by SamuelMereau** [comment]
I am also seeing the same issue running the mod on a server, same error as above for me.

OS: Ubuntu 22.04
Forge Version: 1.19.2 - 43.3.5
Northstar version: 0.1a

**Comment by BraveJamstar** [comment]
As of 8/4/24, The dev fixed multiplayer. However, adding the mod to a server still crashes it. What I was able to find out is adding ICU from earlier to the server mod fixes the crash and the game runs normally. When doing this for the client, the game doesn't launch. It looks like if the dev wanted to support the server version of forge. He would have two separate mods, one for the server and one for the client. So right now until the dev adds the code to make the mod compatible with the server side. We'll most likely have to make our own server side mod manually by adding ICU and building from source.

**Comment by BraveJamstar** [comment]
Turns out you don't need to build another file at all. You just need another mod known as icu4j. After that the server starts without any modification to the file. Just put the file in your mods folder. I will leave a link to the jar file I have. Sorry for any confusion I may have caused earlier. But I have this helps

Link: https://github.com/unicode-org/icu/releases/download/release-75-1/icu4j-75.1.jar

**Comment by Sushiburger1** [comment]
> Turns out you don't need to build another file at all. You just need another mod known as icu4j on the server side. After that the server starts without any modification to the file. Just put the file in your mods folder. I will leave a link to the jar file I have. Sorry for any confusion I may have caused earlier. But I have this helps
> 
> Link: https://github.com/unicode-org/icu/releases/download/release-75-1/icu4j-75.1.jar

when I use this mod, it still gives the same error

**Comment by BraveJamstar** [comment]
Uh ok. That's strange. It worked for me when I did it. What version of minecraft are you using? Also just making sure, you have geckolib and create as well, Right?

I can give you my build if you want to try with that.

**Comment by Sushiburger1** [comment]
> Uh ok. That's strange. It worked for me when I did it. What version of minecraft are you using? Also just making sure, you have geckolib and create as well, Right?
> 
> I can give you my build if you want to try with that.

1.19.2, and I have both geckolib and create, still the same error

**Comment by OutCraft-Mods** [comment]
I think I fixed this issue in my PR #40, can anyone of you try it out?

**Comment by BraveJamstar** [comment]
That might actually work. I'll start testing it out.

**Comment by BetaKale** [comment]
@BraveJamstar Did you get it working?

**Comment by BraveJamstar** [comment]
I did get it to work. I loaded into the game and everything worked. So turns out the change that OutCraft-Mods made to the code actually fixed the error. Now we wait for the dev to merge the code. For now we can compile from OutCraft-Mods' repo. Should work fine.

**Comment by BetaKale** [comment]
> I did get it to work. I loaded into the game and everything worked. So turns out the change that OutCraft-Mods made to the code actually fixed the error. Now we wait for the dev to merge the code. For now we can compile from OutCraft-Mods' repo. Should work fine.

Anychance you could either send me your complied mod or teach me how? I haven't been able to figure out how to do it. My discord is BetaKale if you just want to dm me

**Comment by BraveJamstar** [comment]
I can send you the compiled mod. But if you'd like to learn how to do it. First, You need to install java if you don't already have it. Second, download the OutCraft-Mods' repo and open a command prompt in that folder. You can do this by clicking on the path and typing in `cmd`. Next, Run `gradlew build` and wait. This might take a few minutes. The built file should be in `build/libs`. This is for windows.

The path thing I'm talking about:
![Screenshot 2024-08-07 124805](https://github.com/user-attachments/assets/15dbd1a6-94f7-4ff8-8333-598f3e166875)

But if you want my built file:
[Northstar-1.19.2.zip](https://github.com/user-attachments/files/16531829/Northstar-1.19.2.zip)
You need to use this file for both the server and the client.

Hope this helps.

**Comment by OutCraft-Mods** [comment]
Ohh you send it as zip! I tried uploading a jar but GitHub didn't let me... learned something new I guess!

**Comment by Sushiburger1** [comment]
> I can send you the compiled mod. But if you'd like to learn how to do it. First, You need to install java if you don't already have it. Second, download the OutCraft-Mods' repo and open a command prompt in that folder. You can do this by clicking on the path and typing in `cmd`. Next, Run `gradlew build` and wait. This might take a few minutes. The built file should be in `build/libs`. This is for windows.
> 
> The path thing I'm talking about: ![Screenshot 2024-08-07 124805](https://private-user-images.githubusercontent.com/177088482/355908993-15dbd1a6-94f7-4ff8-8333-598f3e166875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjIyNjksIm5iZiI6MTcyMzE2MTk2OSwicGF0aCI6Ii8xNzcwODg0ODIvMzU1OTA4OTkzLTE1ZGJkMWE2LTk0ZjctNGZmOC04MzMzLTU5OGYzZTE2Njg3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwMDA2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2I2YjliN2UyNWQ2YWFlN2E0YzZiYTQwNTc3YzUyNmEzNzcxZmUwZTMwNTdhZDJhNjQzNGExYTYzZTIyNmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vHqsRWmwPPOG-Ks50HFH488J95GYW2A2ZXuGmYRSZh0)
> 
> But if you want my built file: [Northstar-1.19.2.zip](https://github.com/user-attachments/files/16531829/Northstar-1.19.2.zip) You need to use this file for both the server and the client.
> 
> Hope this helps.

not to sound like a broken record, but that is still giving me the same error. I may just be dumb but at this point ill just wait to add it to my modpack till its officially fixed.

**Comment by Sushiburger1** [comment]
> > I can send you the compiled mod. But if you'd like to learn how to do it. First, You need to install java if you don't already have it. Second, download the OutCraft-Mods' repo and open a command prompt in that folder. You can do this by clicking on the path and typing in `cmd`. Next, Run `gradlew build` and wait. This might take a few minutes. The built file should be in `build/libs`. This is for windows.
> > The path thing I'm talking about: ![Screenshot 2024-08-07 124805](https://private-user-images.githubusercontent.com/177088482/355908993-15dbd1a6-94f7-4ff8-8333-598f3e166875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjIyNjksIm5iZiI6MTcyMzE2MTk2OSwicGF0aCI6Ii8xNzcwODg0ODIvMzU1OTA4OTkzLTE1ZGJkMWE2LTk0ZjctNGZmOC04MzMzLTU5OGYzZTE2Njg3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwMDA2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2I2YjliN2UyNWQ2YWFlN2E0YzZiYTQwNTc3YzUyNmEzNzcxZmUwZTMwNTdhZDJhNjQzNGExYTYzZTIyNmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vHqsRWmwPPOG-Ks50HFH488J95GYW2A2ZXuGmYRSZh0)
> > But if you want my built file: [Northstar-1.19.2.zip](https://github.com/user-attachments/files/16531829/Northstar-1.19.2.zip) You need to use this file for both the server and the client.
> > Hope this helps.
> 
> not to sound like a broken record, but that is still giving me the same error. I may just be dumb but at this point ill just wait to add it to my modpack till its officially fixed.

i sort of lied, its still a problem with mixins but it seems to be problems with more mixins. ill link a txt file of it rq
[error.txt](https://github.com/user-attachments/files/16554372/error.txt)

**Comment by BraveJamstar** [comment]
That's strange. That should have worked. At this point I don't know what's going on. Sorry, I wish I could help more

**Comment by Sushiburger1** [comment]
> That's strange. That should have worked. At this point I don't know what's going on. Sorry, I wish I could help more

newest patch works!! thank you so much everyone!
